### ISSUE TITLE
多次重启后，会出现报错导致无法启动

### ISSUE THREAD

**Issue by chenhengjie123** [SonicCloudOrg/sonic-ios-bridge#21]
考虑到 wda 长期运行稳定性问题，目前我司的云真机 wda 管理策略是：每次使用完毕释放设备时，会自动重启 wda ，重启后检查失败（会检查 sib 进程是否存在、wda status 接口是否通、mjpeg 端口是否通，三个都通过才视为成功）的话会继续自动重启，连续10次重启失败，会重启 ios 设备后再重试

设定了每隔20分钟跑一次自动化，在3台机器上跑了一晚上，启动情况如下：

设备1：iPhone 11 ，iOS: 14.4.2
共重启226次，只有13次成功启动了 wda 服务。

其中74次启动返回
```
WebDriverAgent server start failed... try to mount developer disk image...
mount develop disk image fail
```

127次启动返回
```
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/electricbubble/gidevice.(*device).XCTest(0xc0001bc5b0, {0x7ffeefbff2fe, 0x2b}, {0xc000134110, 0x1, 0x323000?})
	C:/Users/ZHOUYIXUN/go/pkg/mod/github.com/electricbubble/gidevice@v0.4.0/device.go:622 +0x1e34
github.com/SonicCloudOrg/sonic-ios-bridge/cmd.glob..func11(0x1756aa0?, {0x1448324?, 0x8?, 0x8?})
	C:/Users/ZHOUYIXUN/Desktop/sonic-ios-bridge/cmd/wda.go:53 +0x4b2
github.com/spf13/cobra.(*Command).execute(0x1756aa0, {0xc0001be080, 0x8, 0x8})
	C:/Users/ZHOUYIXUN/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x1757720)
	C:/Users/ZHOUYIXUN/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	C:/Users/ZHOUYIXUN/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/SonicCloudOrg/sonic-ios-bridge/cmd.Execute()
	C:/Users/ZHOUYIXUN/Desktop/sonic-ios-bridge/cmd/root.go:32 +0x25
main.main()
	C:/Users/ZHOUYIXUN/Desktop/sonic-ios-bridge/main.go:6 +0x17
```

12次启动返回
```
WebDriverAgent server start failed... try to mount developer disk image...
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/electricbubble/gidevice.(*device).XCTest(0xc0001bc5b0, {0x7ffeefbff2fe, 0x2b}, {0xc000134040, 0x1, 0xc0001ff1c9?})
	C:/Users/ZHOUYIXUN/go/pkg/mod/github.com/electricbubble/gidevice@v0.4.0/device.go:622 +0x1e34
github.com/SonicCloudOrg/sonic-ios-bridge/cmd.glob..func11(0x1756aa0?, {0x1448324?, 0x8?, 0x8?})
	C:/Users/ZHOUYIXUN/Desktop/sonic-ios-bridge/cmd/wda.go:74 +0x8ea
github.com/spf13/cobra.(*Command).execute(0x1756aa0, {0xc0001be080, 0x8, 0x8})
	C:/Users/ZHOUYIXUN/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x1757720)
	C:/Users/ZHOUYIXUN/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	C:/Users/ZHOUYIXUN/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/SonicCloudOrg/sonic-ios-bridge/cmd.Execute()
	C:/Users/ZHOUYIXUN/Desktop/sonic-ios-bridge/cmd/root.go:32 +0x25
main.main()
	C:/Users/ZHOUYIXUN/Desktop/sonic-ios-bridge/main.go:6 +0x17
```

下面是完整的日志文件记录，可根据第一列的内容行数来判定是否有正常启动。
```
       2 wda_log_sib_000080_20220325_001724.log
       2 wda_log_sib_000080_20220325_001851.log.atxClose
       2 wda_log_sib_000080_20220325_002006.log.atxClose
       2 wda_log_sib_000080_20220325_002133.log.atxClose
       2 wda_log_sib_000080_20220325_002248.log.atxClose
       2 wda_log_sib_000080_20220325_002415.log.atxClose
       2 wda_log_sib_000080_20220325_002531.log.atxClose
       2 wda_log_sib_000080_20220325_002657.log
       2 wda_log_sib_000080_20220325_002914.log
       2 wda_log_sib_000080_20220325_003130.log
       2 wda_log_sib_000080_20220325_003346.log
       2 wda_log_sib_000080_20220325_003650.log
       2 wda_log_sib_000080_20220325_004050.log
       2 wda_log_sib_000080_20220325_004449.log
       2 wda_log_sib_000080_20220325_004847.log.atxClose
    9686 wda_log_sib_000080_20220325_005121.log.atxClose
       2 wda_log_sib_000080_20220325_010852.log
      33 wda_log_sib_000080_20220325_011019.log.atxClose
    9892 wda_log_sib_000080_20220325_011040.log.atxClose
   13559 wda_log_sib_000080_20220325_013756.log.atxClose
       2 wda_log_sib_000080_20220325_015741.log
       2 wda_log_sib_000080_20220325_015908.log.atxClose
       2 wda_log_sib_000080_20220325_020024.log.atxClose
       2 wda_log_sib_000080_20220325_020151.log.atxClose
       2 wda_log_sib_000080_20220325_020308.log.atxClose
       2 wda_log_sib_000080_20220325_020434.log.atxClose
       2 wda_log_sib_000080_20220325_020551.log.atxClose
       2 wda_log_sib_000080_20220325_020718.log
      11 wda_log_sib_000080_20220325_020934.log
       2 wda_log_sib_000080_20220325_021150.log
       2 wda_log_sib_000080_20220325_021406.log
       2 wda_log_sib_000080_20220325_021622.log
       2 wda_log_sib_000080_20220325_021838.log
       2 wda_log_sib_000080_20220325_022054.log
       2 wda_log_sib_000080_20220325_022310.log.atxClose
    9622 wda_log_sib_000080_20220325_022451.log.atxClose
       2 wda_log_sib_000080_20220325_024311.log
      32 wda_log_sib_000080_20220325_024437.log.atxClose
    9840 wda_log_sib_000080_20220325_024458.log.atxClose
   13166 wda_log_sib_000080_20220325_031723.log.atxClose
       2 wda_log_sib_000080_20220325_042142.log
       2 wda_log_sib_000080_20220325_042309.log.atxClose
       2 wda_log_sib_000080_20220325_042440.log.atxClose
       2 wda_log_sib_000080_20220325_042607.log.atxClose
       2 wda_log_sib_000080_20220325_042738.log.atxClose
       2 wda_log_sib_000080_20220325_042904.log.atxClose
       2 wda_log_sib_000080_20220325_043036.log.atxClose
       2 wda_log_sib_000080_20220325_043203.log
       2 wda_log_sib_000080_20220325_043424.log
       2 wda_log_sib_000080_20220325_043641.log
       2 wda_log_sib_000080_20220325_043857.log
       2 wda_log_sib_000080_20220325_044113.log
       2 wda_log_sib_000080_20220325_044330.log
       2 wda_log_sib_000080_20220325_044546.log
       2 wda_log_sib_000080_20220325_044803.log.atxClose
    9705 wda_log_sib_000080_20220325_044944.log.atxClose
       2 wda_log_sib_000080_20220325_050759.log
      32 wda_log_sib_000080_20220325_050926.log.atxClose
    9964 wda_log_sib_000080_20220325_050947.log.atxClose
   15917 wda_log_sib_000080_20220325_053804.log.atxClose
       2 wda_log_sib_000080_20220325_055742.log
       2 wda_log_sib_000080_20220325_055908.log.atxClose
       2 wda_log_sib_000080_20220325_060025.log.atxClose
       2 wda_log_sib_000080_20220325_060151.log.atxClose
       2 wda_log_sib_000080_20220325_060308.log.atxClose
       2 wda_log_sib_000080_20220325_060506.log
       2 wda_log_sib_000080_20220325_060622.log.atxClose
       2 wda_log_sib_000080_20220325_060815.log
       2 wda_log_sib_000080_20220325_061038.log
       2 wda_log_sib_000080_20220325_061255.log
       2 wda_log_sib_000080_20220325_061512.log
       2 wda_log_sib_000080_20220325_061728.log
       2 wda_log_sib_000080_20220325_061945.log
       2 wda_log_sib_000080_20220325_062201.log
       2 wda_log_sib_000080_20220325_062417.log.atxClose
    9697 wda_log_sib_000080_20220325_062601.log.atxClose
      34 wda_log_sib_000080_20220325_064421.log.atxClose
    9926 wda_log_sib_000080_20220325_064508.log.atxClose
    9929 wda_log_sib_000080_20220325_071815.log.atxClose
      34 wda_log_sib_000080_20220325_073807.log.atxClose
       2 wda_log_sib_000080_20220325_073854.log
       2 wda_log_sib_000080_20220325_074020.log.atxClose
       2 wda_log_sib_000080_20220325_074153.log.atxClose
       2 wda_log_sib_000080_20220325_074319.log.atxClose
       2 wda_log_sib_000080_20220325_074451.log.atxClose
       2 wda_log_sib_000080_20220325_074617.log
       2 wda_log_sib_000080_20220325_074833.log
       2 wda_log_sib_000080_20220325_075049.log
      17 wda_log_sib_000080_20220325_075306.log
      17 wda_log_sib_000080_20220325_075421.log
      17 wda_log_sib_000080_20220325_075537.log
      17 wda_log_sib_000080_20220325_075653.log
      17 wda_log_sib_000080_20220325_075808.log
      17 wda_log_sib_000080_20220325_075924.log.atxClose
      18 wda_log_sib_000080_20220325_080005.log
      17 wda_log_sib_000080_20220325_080120.log
      17 wda_log_sib_000080_20220325_080236.log
      17 wda_log_sib_000080_20220325_080352.log
      17 wda_log_sib_000080_20220325_080507.log
      17 wda_log_sib_000080_20220325_080623.log
      17 wda_log_sib_000080_20220325_080739.log
      17 wda_log_sib_000080_20220325_080854.log
      17 wda_log_sib_000080_20220325_081010.log
      17 wda_log_sib_000080_20220325_081125.log
      17 wda_log_sib_000080_20220325_081302.log.atxClose
      18 wda_log_sib_000080_20220325_081350.log
      17 wda_log_sib_000080_20220325_081506.log
      17 wda_log_sib_000080_20220325_081622.log
      17 wda_log_sib_000080_20220325_081737.log
      17 wda_log_sib_000080_20220325_081853.log
      17 wda_log_sib_000080_20220325_082009.log
      17 wda_log_sib_000080_20220325_082124.log
      17 wda_log_sib_000080_20220325_082240.log
      17 wda_log_sib_000080_20220325_082355.log
      17 wda_log_sib_000080_20220325_082511.log
      17 wda_log_sib_000080_20220325_082627.log.atxClose
      18 wda_log_sib_000080_20220325_082707.log
      17 wda_log_sib_000080_20220325_082823.log
      17 wda_log_sib_000080_20220325_082938.log
      17 wda_log_sib_000080_20220325_083113.log
      17 wda_log_sib_000080_20220325_083254.log
      17 wda_log_sib_000080_20220325_083412.log
      17 wda_log_sib_000080_20220325_083528.log
      17 wda_log_sib_000080_20220325_083643.log
      17 wda_log_sib_000080_20220325_083759.log
      17 wda_log_sib_000080_20220325_083915.log
      17 wda_log_sib_000080_20220325_084030.log.atxClose
      18 wda_log_sib_000080_20220325_084112.log
      17 wda_log_sib_000080_20220325_084227.log
      17 wda_log_sib_000080_20220325_084343.log
      17 wda_log_sib_000080_20220325_084459.log
      17 wda_log_sib_000080_20220325_084614.log
      17 wda_log_sib_000080_20220325_084742.log
      17 wda_log_sib_000080_20220325_084858.log
      17 wda_log_sib_000080_20220325_085014.log
      17 wda_log_sib_000080_20220325_085129.log
      17 wda_log_sib_000080_20220325_085245.log
      17 wda_log_sib_000080_20220325_085401.log.atxClose
      18 wda_log_sib_000080_20220325_085441.log
      17 wda_log_sib_000080_20220325_085710.log
      17 wda_log_sib_000080_20220325_085935.log
      17 wda_log_sib_000080_20220325_090234.log
      17 wda_log_sib_000080_20220325_090532.log
      17 wda_log_sib_000080_20220325_090748.log
      17 wda_log_sib_000080_20220325_091004.log
      17 wda_log_sib_000080_20220325_091221.log
      17 wda_log_sib_000080_20220325_091437.log
      17 wda_log_sib_000080_20220325_091654.log
      17 wda_log_sib_000080_20220325_091910.log.atxClose
      18 wda_log_sib_000080_20220325_091951.log
      17 wda_log_sib_000080_20220325_092127.log
      17 wda_log_sib_000080_20220325_092344.log
      17 wda_log_sib_000080_20220325_092601.log
      17 wda_log_sib_000080_20220325_092717.log
      17 wda_log_sib_000080_20220325_092832.log
      17 wda_log_sib_000080_20220325_092948.log
      17 wda_log_sib_000080_20220325_093104.log
      17 wda_log_sib_000080_20220325_093219.log
      17 wda_log_sib_000080_20220325_093335.log
      17 wda_log_sib_000080_20220325_093451.log.atxClose
      18 wda_log_sib_000080_20220325_093532.log
      17 wda_log_sib_000080_20220325_093648.log
      17 wda_log_sib_000080_20220325_093803.log
      17 wda_log_sib_000080_20220325_093919.log
      17 wda_log_sib_000080_20220325_094035.log
      17 wda_log_sib_000080_20220325_094150.log
      17 wda_log_sib_000080_20220325_094306.log
      17 wda_log_sib_000080_20220325_094422.log
      17 wda_log_sib_000080_20220325_094537.log
      17 wda_log_sib_000080_20220325_094653.log
      17 wda_log_sib_000080_20220325_094808.log.atxClose
      18 wda_log_sib_000080_20220325_094852.log
      17 wda_log_sib_000080_20220325_095008.log
      17 wda_log_sib_000080_20220325_095124.log
      17 wda_log_sib_000080_20220325_095239.log
      17 wda_log_sib_000080_20220325_095355.log
      17 wda_log_sib_000080_20220325_095510.log
      17 wda_log_sib_000080_20220325_095626.log
      17 wda_log_sib_000080_20220325_095742.log
      17 wda_log_sib_000080_20220325_095857.log
      17 wda_log_sib_000080_20220325_100013.log
      17 wda_log_sib_000080_20220325_100129.log.atxClose
      18 wda_log_sib_000080_20220325_100209.log
      17 wda_log_sib_000080_20220325_100325.log
      17 wda_log_sib_000080_20220325_100440.log
      17 wda_log_sib_000080_20220325_100556.log
      17 wda_log_sib_000080_20220325_100712.log
      17 wda_log_sib_000080_20220325_100827.log
      17 wda_log_sib_000080_20220325_100943.log
      17 wda_log_sib_000080_20220325_101059.log
      17 wda_log_sib_000080_20220325_101214.log
      17 wda_log_sib_000080_20220325_101330.log
      17 wda_log_sib_000080_20220325_101445.log.atxClose
      18 wda_log_sib_000080_20220325_101526.log
      17 wda_log_sib_000080_20220325_101642.log
      17 wda_log_sib_000080_20220325_101757.log
      17 wda_log_sib_000080_20220325_101913.log
      17 wda_log_sib_000080_20220325_102028.log
      17 wda_log_sib_000080_20220325_102144.log
      17 wda_log_sib_000080_20220325_102314.log
      17 wda_log_sib_000080_20220325_102430.log
      17 wda_log_sib_000080_20220325_102546.log
      17 wda_log_sib_000080_20220325_102701.log
      17 wda_log_sib_000080_20220325_102817.log.atxClose
      18 wda_log_sib_000080_20220325_102857.log
      17 wda_log_sib_000080_20220325_103013.log
      17 wda_log_sib_000080_20220325_103129.log
      17 wda_log_sib_000080_20220325_103244.log
      17 wda_log_sib_000080_20220325_103400.log
      17 wda_log_sib_000080_20220325_103515.log
      17 wda_log_sib_000080_20220325_103631.log
      17 wda_log_sib_000080_20220325_103747.log
      17 wda_log_sib_000080_20220325_103902.log
      17 wda_log_sib_000080_20220325_104018.log
      17 wda_log_sib_000080_20220325_104134.log.atxClose
      18 wda_log_sib_000080_20220325_104214.log
      17 wda_log_sib_000080_20220325_104330.log
      17 wda_log_sib_000080_20220325_104445.log
      17 wda_log_sib_000080_20220325_104601.log
      17 wda_log_sib_000080_20220325_104717.log
      17 wda_log_sib_000080_20220325_105018.log
      17 wda_log_sib_000080_20220325_105443.log
      17 wda_log_sib_000080_20220325_105907.log
      17 wda_log_sib_000080_20220325_110206.log
      17 wda_log_sib_000080_20220325_110338.log
      17 wda_log_sib_000080_20220325_110555.log
```

**Comment by ZhouYixun** [comment]
不应该，我继续看下

**Comment by ZhouYixun** [comment]
请问用的wda是appium的吗，相关启动代码有没有。
有时候代码出问题，会导致wda崩溃掉，然后需要重新打wda

**Comment by ZhouYixun** [comment]
我询问下gidevice那边，目前好像不是挂载镜像的问题，只是启动wda失败的err不为空，我又进行了一次挂载

**Comment by chenhengjie123** [comment]
> 

用的是基于 appium 的 wda 调整的 wda 。调整内容为重启后若传入 session id ，则自动创建对应 session ，用于兼容重启后 appium 用老的 session 继续执行这个场景。

不大理解需要重新打 wda 是什么意思，同样版本的 wda 用 tidevice 启动，从来没出现过 wda 应用本身会消失掉的情况。

**Comment by chenhengjie123** [comment]
看是否能给一个失败后会产生更详细报错错误信息的 sib 包，我替换下再看看？或者告知我有没有类似 --debug 这类打印更详细日志的参数，我加上？

**Comment by ZhouYixun** [comment]
> 看是否能给一个失败后会产生更详细报错错误信息的 sib 包，我替换下再看看？或者告知我有没有类似 --debug 这类打印更详细日志的参数，我加上？

目前有看到报错了，但是手上没有设备，下周我看看

**Comment by ZhouYixun** [comment]
已知跟tidevice共存会发生冲突，我先关闭这个issue，后续争取兼容
